app = 'orchestrator-back'
primary_region = 'iad'

[build]
  image = 'ghcr.io/flyio/java-buildpack:latest'  # Buildpack oficial para Java

[env]
  SPRING_PROFILES_ACTIVE = "prod"
  JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Dserver.address=0.0.0.0"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1  # Mínimo de 1 máquina para evitar downtime

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
